# Generated by Django 5.1.2 on 2025-05-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("urunler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IsTuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="YapilacakIs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IsEmri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilce", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                (
                    "sonuc",
                    models.CharField(
                        choices=[("olumlu", "Olumlu"), ("olumsuz", "Olumsuz")],
                        max_length=10,
                    ),
                ),
                (
                    "baslangic_fotograf",
                    models.ImageField(
                        blank=True, null=True, upload_to="is_emri/baslangic/"
                    ),
                ),
                (
                    "bitis_fotograf",
                    models.ImageField(
                        blank=True, null=True, upload_to="is_emri/bitis/"
                    ),
                ),
                (
                    "lokasyon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="urunler.lokasyon",
                    ),
                ),
                (
                    "personel1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personel1",
                        to="urunler.personel",
                    ),
                ),
                (
                    "personel2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personel2",
                        to="urunler.personel",
                    ),
                ),
                (
                    "personel3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personel3",
                        to="urunler.personel",
                    ),
                ),
                (
                    "personel4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personel4",
                        to="urunler.personel",
                    ),
                ),
                ("is_turleri", models.ManyToManyField(to="is_emri.isturu")),
                ("yapilacak_isler", models.ManyToManyField(to="is_emri.yapilacakis")),
            ],
        ),
    ]
