# Generated by Django 5.1.2 on 2025-05-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lokasyon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adi", models.CharField(max_length=255)),
                ("minimum_stok", models.PositiveIntegerField(default=0)),
                ("stok_miktari", models.IntegerField(default=0)),
                (
                    "ybs_malzeme_ismi",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ybs_malzeme_kodu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "aciklama1",
                    models.TextField(blank=True, null=True, verbose_name="Marka"),
                ),
                (
                    "aciklama2",
                    models.TextField(blank=True, null=True, verbose_name="Model"),
                ),
                (
                    "aciklama3",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="urunler.kategori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_turu",
                    models.CharField(
                        choices=[("Giriş", "Giriş"), ("Çıkış", "Çıkış")], max_length=10
                    ),
                ),
                ("adet", models.PositiveIntegerField()),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("plaka", models.CharField(blank=True, max_length=20, null=True)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "lokasyon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="urunler.lokasyon",
                    ),
                ),
                (
                    "personel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="urunler.personel",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="urunler.urun"
                    ),
                ),
            ],
        ),
    ]
